version: '2'
services:
  rvdb:
    image: rethinkdb
    volumes:
      - ./rethinkdata:/data
    networks:
      - nignet
    command: rethinkdb --bind all -d /data 
    restart: always
  pythong:
    build: pythong/
    networks:
      - nignet
    restart: always
      
networks:
  nignet:
    driver: bridge
